// frontend/src/app/features/candies/candy-list/candy-list.component.ts
import { Component, OnInit } from '@angular/core'
import { Observable } from 'rxjs'

import { Candy } from 'app/core/api/candy.gateway'
import { CandyQuery, CandyService } from 'app/features/candies/state'

@Component({
  selector: 'app-candy-list',
  templateUrl: './candy-list.component.html',
})
export class CandyListComponent implements OnInit {
  candies$: Observable<Candy[]> = this.candyQuery.sortedList()

  constructor(
    private candyService: CandyService,
    private candyQuery: CandyQuery
  ) {}

  ngOnInit() {
    this.candyService.fetchList().subscribe()
  }
}

<h1 class="title">
  Конфеты
  <button class="button" [routerLink]="['/candies/new']">
    <fa-icon icon="plus"></fa-icon>
  </button>
</h1>

<table class="is-hidden-mobile table is-fullwidth is-striped is-hoverable">
  <thead>
    <tr>
      <th>Название</th>
      <th>Производитель</th>
      <th>Цена</th>
      <th>Порядок</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let candy of candies$ | async">
      <td>{{ candy.name }}</td>
      <td>{{ candy.firm }}</td>
      <td>{{ candy.price | price }}</td>
      <td>{{ candy.order }}</td>
      <td>
        <a [routerLink]="['/candies', candy.id]" class="button is-text">
          <span class="icon">
            <fa-icon icon="eye"></fa-icon>
          </span>
        </a>
      </td>
    </tr>
  </tbody>
</table>

<div class="is-hidden-tablet columns is-multiline">
  <div
    class="column is-one-fifth-desktop is-half-tablet"
    *ngFor="let candy of candies$ | async"
  >
    <a [routerLink]="['/candies', candy.id]">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title">{{ candy.name }}</p>
        </header>
        <div class="card-content">
          <div class="content">
            <p>{{ candy.firm }}</p>
            <p>{{ candy.price | price }}</p>
          </div>
        </div>
      </div>
    </a>
  </div>
</div>

<app-link-border></app-link-border>

// frontend/src/lib/components/candy/CandyList.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import FaEye from 'svelte-icons/fa/FaEye.svelte'
  import { candyRepository } from '$lib/data/candy.repository'
  import { isMobile } from '$lib/utils/responsive.utils'
  import { formatPrice } from '$lib/utils/string.utils'

  let candies = candyRepository.candies

  onMount(() => {
    candyRepository.fetch()
  })
</script>

{#if $isMobile}
  <div class="columns is-multiline">
    {#each $candies as candy (candy.id)}
      <div class="column">
        <a href="/candies/{candy.id}">
          <div class="card">
            <header class="card-header">
              <div class="card-header-title">{candy.name}</div>
            </header>
            <div class="card-content">
              <div class="content">
                <div><strong>Производитель: </strong>{candy.firm}</div>
                <div><strong>Цена: </strong>{formatPrice(candy.price)}</div>
              </div>
            </div>
          </div>
        </a>
      </div>
    {/each}
  </div>
{:else}
  <table class="table is-fullwidth is-striped is-hoverable">
    <thead>
      <tr>
        <th>Название</th>
        <th>Производитель</th>
        <th>Цена</th>
        <th>Порядок</th>
        <th />
      </tr>
    </thead>
    <tbody>
      {#each $candies as candy (candy.id)}
        <tr>
          <td>{candy.name}</td>
          <td>{candy.firm}</td>
          <td>{formatPrice(candy.price)}</td>
          <td>{candy.order}</td>
          <td>
            <a href="/candies/{candy.id}" class="button is-text">
              <span class="icon">
                <FaEye />
              </span>
            </a>
          </td>
        </tr>
      {/each}
    </tbody>
  </table>
{/if}
