// frontend/src/lib/components/presents/PresentList.svelte
<script lang="ts">
  import { presentRepository } from '$lib/present/present.repository'
  import { isMobile } from '$lib/utils/responsive.utils'
  import { formatPrice } from '$lib/utils/string.utils'
  import { onMount } from 'svelte'
  import FaEye from 'svelte-icons/fa/FaEye.svelte'

  let presents = presentRepository.presents

  onMount(() => {
    presentRepository.fetch()
  })
</script>

{#if $isMobile}
  <div class="columns is-multiline">
    {#each $presents as present (present.id)}
      <div class="column">
        <a href="/presents/{present.id}">
          <div class="card">
            <header class="card-header">
              <div class="card-header-title">{present.name}</div>
            </header>
            <div class="card-content">
              <div class="content">
                <div><strong>Цена: </strong>{formatPrice(present.price)}</div>
                <div><strong>Позиций: </strong>{present.items.length}</div>
              </div>
            </div>
          </div>
        </a>
      </div>
    {/each}
  </div>
{:else}
  <table class="table is-fullwidth is-striped is-hoverable">
    <thead>
      <tr>
        <th>Название</th>
        <th>Цена</th>
        <th>Позиций</th>
        <th />
      </tr>
    </thead>
    <tbody>
      {#each $presents as present (present.id)}
        <tr>
          <td>{present.name}</td>
          <td>{formatPrice(present.price)}</td>
          <td>{present.items.length}</td>
          <td>
            <a href="/presents/{present.id}" class="button is-text">
              <span class="icon">
                <FaEye />
              </span>
            </a>
          </td>
        </tr>
      {/each}
    </tbody>
  </table>
{/if}

// frontend/src/app/features/presents/present-list/present-list.component.ts
import { Component } from '@angular/core'
import { Observable } from 'rxjs'

import { PresentGateway } from 'app/core/api/present.gateway'
import { Present } from 'app/core/api/present.dto'

@Component({
  selector: 'app-present-list',
  templateUrl: './present-list.component.html',
})
export class PresentListComponent {
  presents$: Observable<Present[]> = this.presentGateway.list()

  constructor(private presentGateway: PresentGateway) {}
}

<h1 class="title">
  Подарки
  <button class="button" [routerLink]="['/presents/new']">
    <span class="icon">
      <fa-icon icon="plus"></fa-icon>
    </span>
  </button>
</h1>

<table class="is-hidden-mobile table is-fullwidth is-striped is-hoverable">
  <thead>
    <tr>
      <th>Название</th>
      <th>Цена</th>
      <th>Позиций</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let present of presents$ | async">
      <td>{{ present.name }}</td>
      <td>{{ present.price | price }}</td>
      <td>{{ present.items.length }}</td>
      <td>
        <a [routerLink]="['/presents', present.id]" class="button is-text">
          <span class="icon">
            <fa-icon icon="eye"></fa-icon>
          </span>
        </a>
      </td>
    </tr>
  </tbody>
</table>

<div class="is-hidden-tablet columns is-multiline">
  <div class="column" *ngFor="let present of presents$ | async">
    <a [routerLink]="['/presents', present.id]">
      <div class="card">
        <header class="card-header">
          <div class="card-header-title">{{ present.name }}</div>
        </header>
        <div class="card-content">
          <div class="content">
            <div><strong>Цена: </strong>{{ present.price | price }}</div>
            <div><strong>Позиций: </strong>{{ present.items.length }}</div>
          </div>
        </div>
      </div>
    </a>
  </div>
</div>

<app-link-border></app-link-border>
