// frontend/src/app/features/presents/present-new/present-new.component.ts
import { Component, OnInit } from '@angular/core'
import { FormArray, FormBuilder, FormGroup, Validators } from '@angular/forms'
import { ActivatedRoute } from '@angular/router'

import { Candy } from 'app/core/api/candy.gateway'
import { PresentGateway, NewPresentRequest } from 'app/core/api/present.gateway'
import {
  Present,
  PresentItem,
} from 'app/features/presents/service/present.model'
import { PresentService } from 'app/features/presents/service/present.service'
import { NumberValidators, StringValidators } from 'app/core/utils'

@Component({
  selector: 'app-present-new',
  templateUrl: './present-new.component.html',
})
export class PresentNewComponent implements OnInit {
  form: FormGroup

  successAdd = false

  get sourceId(): string {
    return this.route.snapshot.params.source
  }

  get itemsForm(): FormArray {
    return this.form.get('items') as FormArray
  }

  get selectedItems(): PresentItem[] {
    return this.itemsForm.value as PresentItem[]
  }

  get selectedCandies(): Candy[] {
    return this.selectedItems.map((i) => i.candy)
  }

  get present(): Present {
    return new Present(this.form.value, this.selectedCandies)
  }

  constructor(
    private fb: FormBuilder,
    private route: ActivatedRoute,
    private presentService: PresentService,
    private presentGateway: PresentGateway
  ) {
    this.form = fb.group({
      name: ['', [StringValidators.notEmpty, StringValidators.maxLength(50)]],
      price: [
        '',
        [
          Validators.required,
          Validators.min(1),
          NumberValidators.maxFractionLength(2),
        ],
      ],
      items: fb.array([], Validators.required),
    })
  }

  ngOnInit() {
    if (this.sourceId) {
      this.presentService
        .getPresent(this.sourceId)
        .subscribe((present) =>
          present.items.forEach((item) => this.upsertItem(item))
        )
    }
  }

  onItemCountChange(item: PresentItem) {
    if (item.count <= 0) {
      this.removeItem(item.candy)
    } else {
      this.upsertItem(item)
    }
  }

  upsertItem(item: PresentItem) {
    const index = this.itemsForm.controls.findIndex(
      (i) => i.value.candyId === item.candy.id
    )
    if (index !== -1) {
      this.itemsForm.controls[index].patchValue({count: item.count})
    } else {
      this.itemsForm.push(this.buildItemForm(item))
    }
  }

  private buildItemForm(item: PresentItem) {
    return this.fb.group({
      count: [
        item.count,
        [
          Validators.required,
          Validators.min(1),
          NumberValidators.maxFractionLength(0),
        ],
      ],
      candyId: item.candy.id,
      candy: this.fb.group(item.candy),
    })
  }

  removeItem(candy: Candy) {
    const index = this.itemsForm.controls.findIndex(
      (item) => item.value.candyId === candy.id
    )

    this.itemsForm.removeAt(index)
  }

  onSubmit() {
    this.form.markAllAsTouched()
    if (this.form.valid) {
      this.add(this.form.value)
    }
  }

  private add(addReq: NewPresentRequest) {
    this.presentGateway.add(addReq).subscribe(() => {
      this.notifyAdd()
      this.itemsForm.clear()
      this.form.reset()
    })
  }

  private notifyAdd() {
    this.successAdd = true
    setTimeout(() => {
      this.successAdd = false
    }, 5000)
  }
}

<h1 class="title">Новый подарок</h1>

<div *ngIf="successAdd" class="notification is-primary">Добавлено</div>

<form [formGroup]="form" (ngSubmit)="onSubmit()">
  <div class="field">
    <label class="label">Название</label>
    <div class="control">
      <input class="input" formControlName="name" appFormControl />
    </div>
  </div>
  <div class="field">
    <label class="label">Цена</label>
    <div class="control">
      <input
        class="input"
        type="number"
        placeholder="Пример: 123.12"
        formControlName="price"
        appFormControl
      />
    </div>
  </div>
  <div class="field">
    <div class="control">
      <button type="submit" class="button is-primary">
        <span class="icon">
          <fa-icon icon="plus"></fa-icon>
        </span>
        <span>Добавить</span>
      </button>
    </div>
  </div>
  <div class="field">
    <label class="label">Себестоимость</label>
    <div class="control">
      {{ present.cost | price }}
    </div>
  </div>
  <div class="field">
    <label class="label">Состав</label>

    <details formArrayName="items" appFormControl>
      <summary>Позиций: {{ itemsForm.controls.length }}</summary>
      <table class="table is-fullwidth">
        <tbody>
          <tr>
            <th>Название</th>
            <th>Производитель</th>
            <th>Цена</th>
            <th>Кол-во</th>
          </tr>

          <tr
            *ngFor="let item of itemsForm.controls; let i = index"
            [formGroupName]="i"
          >
            <td>{{ item.value.candy.name }}</td>
            <td>{{ item.value.candy.firm }}</td>
            <td>{{ item.value.candy.price | price }}</td>
            <td>
              <app-present-item-control
                [currentCount]="item.value.count"
                (newCount)="
                  onItemCountChange({ candy: item.value.candy, count: $event })
                "
              ></app-present-item-control>
            </td>
          </tr>
        </tbody>
      </table>
    </details>
  </div>
</form>

<app-present-new-select-candy
  [selectedItems]="selectedItems"
  (changedCount)="onItemCountChange($event)"
></app-present-new-select-candy>

// frontend/src/lib/components/presents/new/PresentNew.svelte
<script lang="ts">
  import { maxLength, required, useForm, validators } from 'svelte-use-form'
  import FaPlus from 'svelte-icons/fa/FaPlus.svelte'
  import { onMount } from 'svelte'
  import CollapsibleCard from '$lib/components/CollapsibleCard.svelte'
  import ErrorHint from '$lib/components/ErrorHint.svelte'
  import FieldError from '$lib/components/FieldError.svelte'
  import ScrollNav from '$lib/components/ScrollNav.svelte'
  import { costByItems } from '$lib/data/present.model'
  import type { Present, PresentItem } from '$lib/data/present.model'
  import { candyRepository } from '$lib/data/candy.repository'
  import { formatPrice } from '$lib/utils/string.utils'
  import type { NewPresentRequest } from '$lib/api/present.api'
  import { toMap } from '$lib/utils/collection.utils'
  import { maxFractionLength, min } from '$lib/utils/number.validators'
  import { presentRepository } from '$lib/data/present.repository'
  import SelectCandy from './SelectCandy.svelte'
  import PresentItemList from './PresentItemList.svelte'

  export let source: Present | undefined

  let data: NewPresentRequest = initData()

  function initData(): NewPresentRequest {
    return {
      name: '',
      price: 1,
      items: [],
    }
  }

  const form = useForm()
  let added = false
  let saveButtonElement: HTMLElement
  let cost: number
  $: cost = costByItems(data.items, candyRepository.queryByItems(data.items))
  $: emptyItems = data.items.length === 0

  onMount(async () => {
    await candyRepository.fetch()
    if (source) {
      const activeSourceCandies = toMap(
        candyRepository.queryByItems(source.items),
        'id'
      )

      data = {
        ...source,
        items: source.items.filter((i) => activeSourceCandies.has(i.candyId)),
      }
    }
  })

  function onChangeItem(item: PresentItem) {
    if (item.count > 0) {
      const currentItem = data.items.find((i) => i.candyId === item.candyId)
      if (currentItem) {
        currentItem.count = item.count
      } else {
        data.items.push(item)
      }
      data.items = data.items
    } else {
      data.items = data.items.filter((i) => i.candyId !== item.candyId)
    }
  }

  async function onSave() {
    $form.touched = true
    if (!$form.valid || emptyItems) {
      return
    }
    await presentRepository.add(data)
    data = initData()
    added = true
    setTimeout(() => (added = false), 3000)
  }
</script>

<h1 class="title">Новый подарок</h1>

{#if added}
  <div class="notification is-primary">Добавлено</div>
{/if}

<form use:form on:submit|preventDefault={onSave}>
  <div class="field">
    <label class="label" for="name">Название</label>
    <div class="control">
      <input
        class="input"
        name="name"
        bind:value={data.name}
        use:validators={[required, maxLength(50)]}
      />
    </div>
    <FieldError field={$form.name} />
  </div>
  <div class="field">
    <label class="label" for="price">Цена</label>
    <div class="control">
      <input
        class="input"
        type="number"
        placeholder="Пример: 123.12"
        name="price"
        bind:value={data.price}
        use:validators={[required, min(1), maxFractionLength(2)]}
      />
    </div>
    <FieldError field={$form.price} />
  </div>
  <div class="field">
    <div class="control">
      <button
        type="button"
        class="button is-primary"
        on:click={onSave}
        bind:this={saveButtonElement}
      >
        <span class="icon">
          <FaPlus />
        </span>
        <span>Добавить</span>
      </button>
    </div>
  </div>
  <div class="field">
    <div class="label">Себестоимость</div>
    <div class="control">
      {formatPrice(cost)}
    </div>
  </div>
  <div class="field">
    <div class="label">Состав</div>

    <CollapsibleCard expanded={false} disabled={emptyItems}>
      <span slot="title">Позиций: {data.items.length}</span>
      <div class="content">
        <PresentItemList
          items={data.items}
          on:change={(event) => onChangeItem(event.detail)}
        />
      </div>
    </CollapsibleCard>
    {#if $form.touched && emptyItems}
      <ErrorHint message="отсутствует" />
    {/if}
  </div>
</form>

<SelectCandy
  items={data.items}
  on:change={(event) => onChangeItem(event.detail)}
/>

<ScrollNav
  message={'Себестоимость: ' + formatPrice(cost)}
  anchorElement={saveButtonElement}
/>
