// frontend/src/app/shared/components/scroll-nav/scroll-nav.component.ts
import { ScrollDispatcher } from '@angular/cdk/scrolling'
import { DOCUMENT } from '@angular/common'
import { Component, Inject, Input, NgZone } from '@angular/core'
import { isScrolledIntoView } from 'app/core/utils'
import { debounceTime, map } from 'rxjs/operators'

@Component({
  selector: 'app-scroll-nav',
  templateUrl: './scroll-nav.component.html',
})
export class ScrollNavComponent {
  @Input()
  message: string = ''

  @Input()
  scrollElement!: HTMLElement

  isVisible: boolean = false

  constructor(
    @Inject(DOCUMENT) private document: Document,
    scrollDispatcher: ScrollDispatcher,
    ngZone: NgZone
  ) {
    scrollDispatcher
      .scrolled()
      .pipe(
        debounceTime(50),
        map(() => !isScrolledIntoView(this.scrollElement))
      )
      .subscribe((res) => ngZone.run(() => this.onVisibleChange(res)))
  }

  onVisibleChange(visible: boolean) {
    this.isVisible = visible
    if (visible) {
      this.document.body.classList.add('has-navbar-fixed-bottom')
    } else {
      this.document.body.classList.remove('has-navbar-fixed-bottom')
    }
  }

  scrollToElement() {
    this.scrollElement.scrollIntoView()
  }
}

<nav class="navbar is-transparent is-fixed-bottom" *ngIf="isVisible">
  <div class="navbar-menu is-active">
    <div class="navbar-end">
      <div class="navbar-item">
        {{ message }}
      </div>
      <div class="navbar-item">
        <div class="field is-grouped">
          <p class="control">
            <a class="button is-primary" (click)="scrollToElement()">
              <span class="icon">
                <fa-icon icon="eye"></fa-icon>
              </span>
              <span>Подробнее</span>
            </a>
          </p>
        </div>
      </div>
    </div>
  </div>
</nav>

// frontend/src/lib/components/ScrollNav.svelte
<script lang="ts">
  import FaEye from 'svelte-icons/fa/FaEye.svelte'

  export let message: string
  export let anchorElement: HTMLElement

  let scrollY: number
  let visible = false
  $: scrollY, (visible = anchorElement && !isScrolledIntoView(anchorElement))
  $: if (visible) {
    document.body.classList.add('has-navbar-fixed-bottom')
  } else {
    document.body.classList.remove('has-navbar-fixed-bottom')
  }

  function isScrolledIntoView(el: HTMLElement): boolean {
    const rect = el.getBoundingClientRect()
    return rect.bottom >= 0
  }

  function scrollToAnchor() {
    anchorElement.scrollIntoView()
  }
</script>

<svelte:window bind:scrollY />

{#if visible}
  <nav class="navbar is-transparent is-fixed-bottom">
    <div class="navbar-menu is-active">
      <div class="navbar-end">
        <div class="navbar-item">
          {message}
        </div>
        <div class="navbar-item">
          <div class="field is-grouped">
            <p class="control">
              <!-- svelte-ignore a11y-missing-attribute -->
              <a class="button is-primary" on:click={scrollToAnchor}>
                <span class="icon">
                  <FaEye />
                </span>
                <span>Подробнее</span>
              </a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </nav>
{/if}
